### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by maguirekrist** [maguirekrist/Unity-RPG-game#1]
## TODO:
- [x] Render map with collision
- [ ] Player movement
- [ ] Player animation
- [ ] Player health and lives
- [ ] Player attack and weapons/spells
- [ ] NPC's
- [ ] Path finding system
- [ ] Enemies 
- [ ] Inventory system
- [ ] Player GUI
- [ ] Game GUI
- [ ] Settings GUI
- [ ] Quests
- [ ] Items
- [ ] Armor
